DROP TABLE IF EXISTS tickets;

CREATE TABLE tickets(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL,
problem VARCHAR(1000) NOT NULL,
priority INT NOT NULL,
closed BOOLEAN NOT NULL DEFAULT FALSE,
created_date DATE NOT NULL DEFAULT CURRENT_DATE,
closed_date DATE
);